-- MySQL Script generated by MySQL Workbench
-- Sun Mar 11 02:19:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_carmaker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_carmaker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_carmaker` DEFAULT CHARACTER SET utf8 ;
USE `db_carmaker` ;

-- -----------------------------------------------------
-- Table `db_carmaker`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_carmaker`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `register` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `photo` LONGBLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `register_UNIQUE` (`register` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_carmaker`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_carmaker`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `production_time` INT NOT NULL,
  `cost_price` DOUBLE NOT NULL,
  `sale_price` DOUBLE NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_car_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_car_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `db_carmaker`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_carmaker`.`feedstock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_carmaker`.`feedstock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quantityPerLot` INT NOT NULL,
  `costPerLot` DOUBLE NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feedstock_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_feedstock_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `db_carmaker`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_carmaker`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_carmaker`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `protocol` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `expected_date` DATE NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_employee_idx` (`employee_id` ASC),
  CONSTRAINT `fk_order_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `db_carmaker`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_carmaker`.`shipping_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_carmaker`.`shipping_company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount_per_transport` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shipping_company_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_shipping_company_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `db_carmaker`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_carmaker`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_carmaker`.`supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lead_time` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `employee_id` INT NOT NULL,
  `feedstock_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier_employee1_idx` (`employee_id` ASC),
  INDEX `fk_supplier_feedstock1_idx` (`feedstock_id` ASC),
  CONSTRAINT `fk_supplier_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `db_carmaker`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_feedstock1`
    FOREIGN KEY (`feedstock_id`)
    REFERENCES `db_carmaker`.`feedstock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_carmaker`.`order_has_shipping_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_carmaker`.`order_has_shipping_company` (
  `order_id` INT NOT NULL,
  `shipping_company_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `shipping_company_id`),
  INDEX `fk_order_has_shipping_company_shipping_company1_idx` (`shipping_company_id` ASC),
  INDEX `fk_order_has_shipping_company_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_has_shipping_company_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `db_carmaker`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_shipping_company_shipping_company1`
    FOREIGN KEY (`shipping_company_id`)
    REFERENCES `db_carmaker`.`shipping_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_carmaker`.`order_has_supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_carmaker`.`order_has_supplier` (
  `order_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `supplier_id`),
  INDEX `fk_order_has_supplier_supplier1_idx` (`supplier_id` ASC),
  INDEX `fk_order_has_supplier_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_has_supplier_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `db_carmaker`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_supplier_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `db_carmaker`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_carmaker`.`dealership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_carmaker`.`dealership` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `shipping_company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dealership_shipping_company1_idx` (`shipping_company_id` ASC),
  CONSTRAINT `fk_dealership_shipping_company1`
    FOREIGN KEY (`shipping_company_id`)
    REFERENCES `db_carmaker`.`shipping_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_carmaker`.`dealership_has_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_carmaker`.`dealership_has_order` (
  `dealership_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`dealership_id`, `order_id`),
  INDEX `fk_dealership_has_order_order1_idx` (`order_id` ASC),
  INDEX `fk_dealership_has_order_dealership1_idx` (`dealership_id` ASC),
  CONSTRAINT `fk_dealership_has_order_dealership1`
    FOREIGN KEY (`dealership_id`)
    REFERENCES `db_carmaker`.`dealership` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dealership_has_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `db_carmaker`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
