/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.carmaker.view.panel;

import br.carmaker.model.util.JConstants;
import br.carmaker.model.JDbFacade;
import br.carmaker.model.JDealership;
import br.carmaker.model.JShippingCompany;
import br.carmaker.model.JSupplier;
import br.carmaker.model.enums.EAffiliate;
import br.carmaker.model.enums.EMenuItem;
import br.carmaker.view.dialog.ConfirmDialog;
import br.carmaker.view.dialog.RegisterDialog;
import br.carmaker.view.list.DealershipList;
import br.carmaker.view.list.ShippingCompanyList;
import br.carmaker.view.list.SupplierList;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author Usuário
 */
public class AffiliatePanel extends javax.swing.JPanel {

    /**
     * Creates new form AffiliatePanel
     */
    public AffiliatePanel(JFrame frame) {
        initComponents();
        this.mainFrame = frame;
        initLists();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddAffiliates = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        supplierPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSupplier = new javax.swing.JList<>();
        shippingCompanyPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listShippingCompany = new javax.swing.JList<>();
        dealershipPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDealership = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        btnAddAffiliates.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnAddAffiliates.setText("Adicionar novo");
        btnAddAffiliates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddAffiliatesMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setText("Lista de Afiliadas: ");

        cardPanel.setLayout(new java.awt.CardLayout());

        listSupplier.setModel(dlmSupplier);
        listSupplier.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listSupplier.setCellRenderer(new SupplierList());
        listSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listSupplierMouseClicked(evt);
            }
        });
        listSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listSupplierKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listSupplier);

        javax.swing.GroupLayout supplierPanelLayout = new javax.swing.GroupLayout(supplierPanel);
        supplierPanel.setLayout(supplierPanelLayout);
        supplierPanelLayout.setHorizontalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        supplierPanelLayout.setVerticalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardPanel.add(supplierPanel, "card4");

        listShippingCompany.setModel(dlmSC);
        listShippingCompany.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listShippingCompany.setCellRenderer(new ShippingCompanyList());
        listShippingCompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listShippingCompanyMouseClicked(evt);
            }
        });
        listShippingCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listShippingCompanyKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(listShippingCompany);

        javax.swing.GroupLayout shippingCompanyPanelLayout = new javax.swing.GroupLayout(shippingCompanyPanel);
        shippingCompanyPanel.setLayout(shippingCompanyPanelLayout);
        shippingCompanyPanelLayout.setHorizontalGroup(
            shippingCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shippingCompanyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        shippingCompanyPanelLayout.setVerticalGroup(
            shippingCompanyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shippingCompanyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardPanel.add(shippingCompanyPanel, "card3");

        listDealership.setModel(dlmDealership);
        listDealership.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDealership.setCellRenderer(new DealershipList());
        listDealership.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDealershipMouseClicked(evt);
            }
        });
        listDealership.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listDealershipKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(listDealership);

        javax.swing.GroupLayout dealershipPanelLayout = new javax.swing.GroupLayout(dealershipPanel);
        dealershipPanel.setLayout(dealershipPanelLayout);
        dealershipPanelLayout.setHorizontalGroup(
            dealershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dealershipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        dealershipPanelLayout.setVerticalGroup(
            dealershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dealershipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardPanel.add(dealershipPanel, "card2");

        jLabel1.setText("Selecione uma afiliada: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fornecedor", "Transportadora", "Concessionária" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(384, 384, 384))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddAffiliates))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAffiliates))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAffiliatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAffiliatesMouseClicked
        this.setEnabled(false);
        RegisterDialog dialog = new RegisterDialog(mainFrame, true, 3, EMenuItem.AFFILIATES);
        dialog.setVisible(true);

        initLists();
    }//GEN-LAST:event_btnAddAffiliatesMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int index = jComboBox1.getSelectedIndex();
        cardPanel.removeAll();

        switch (index) {
            case 1:
                cardPanel.add(shippingCompanyPanel);
                break;
            case 2:
                cardPanel.add(dealershipPanel);
                break;
            default:
                cardPanel.add(supplierPanel);
                break;
        }

        cardPanel.repaint();
        cardPanel.revalidate();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void listDealershipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDealershipMouseClicked
        if (evt.getClickCount() == 2) {
            JDealership dealership = listDealership.getSelectedValue();

            mainFrame.setEnabled(false);
            RegisterDialog dialog = new RegisterDialog(mainFrame, true, 3,
                    EMenuItem.AFFILIATES, dealership, EAffiliate.DEALERSHIP);
            dialog.setVisible(true);
            initDealershipList();
        }
    }//GEN-LAST:event_listDealershipMouseClicked

    private void listShippingCompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listShippingCompanyMouseClicked
        if (evt.getClickCount() == 2) {
            JShippingCompany shippingCompany = listShippingCompany.getSelectedValue();

            mainFrame.setEnabled(false);
            RegisterDialog dialog = new RegisterDialog(mainFrame, true, 3,
                    EMenuItem.AFFILIATES, shippingCompany, EAffiliate.SHIPPING_COMPANY);
            dialog.setVisible(true);
            initDealershipList();
        }
    }//GEN-LAST:event_listShippingCompanyMouseClicked

    private void listSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listSupplierMouseClicked
        if (evt.getClickCount() == 2) {            
            JSupplier supplier = listSupplier.getSelectedValue();

            mainFrame.setEnabled(false);
            RegisterDialog dialog = new RegisterDialog(mainFrame, true, 3,
                    EMenuItem.AFFILIATES, supplier, EAffiliate.SUPPLIER);
            dialog.setVisible(true);
            initDealershipList();
        }
    }//GEN-LAST:event_listSupplierMouseClicked

    private void listSupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listSupplierKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            JSupplier s = listSupplier.getSelectedValue();
            if (s != null && s.getId() != -1) {
                int id = s.getId();
                ConfirmDialog.showConfirmationMessage(mainFrame, JConstants.CONFIRM_DELETE_SUPPLIER, this);
                if (ConfirmDialog.getUserChoice()) {
                    JDbFacade.getInstance().deleteSupplier(id);
                    initSupplierList();
                }
            }

        }
    }//GEN-LAST:event_listSupplierKeyPressed

    private void listShippingCompanyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listShippingCompanyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            JShippingCompany s = listShippingCompany.getSelectedValue();
            if (s != null && s.getId() != -1) {
                int id = s.getId();
                ConfirmDialog.showConfirmationMessage(mainFrame, JConstants.CONFIRM_DELETE_SHIPPING_COMPANY, this);
                if (ConfirmDialog.getUserChoice()) {
                    JDbFacade.getInstance().deleteShippingCompany(id);
                    initShippingCompanyList();
                }
            }

        }
    }//GEN-LAST:event_listShippingCompanyKeyPressed

    private void listDealershipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listDealershipKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            JDealership d = listDealership.getSelectedValue();

            if (d != null) {
                int id = d.getId();
                ConfirmDialog.showConfirmationMessage(mainFrame, JConstants.CONFIRM_DELETE_DEALERSHIP, this);
                if (ConfirmDialog.getUserChoice()) {
                    JDbFacade.getInstance().deleteDealership(id);
                    initDealershipList();
                }
            }

        }
    }//GEN-LAST:event_listDealershipKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAffiliates;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel dealershipPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<JDealership> listDealership;
    private javax.swing.JList<JShippingCompany> listShippingCompany;
    private javax.swing.JList<JSupplier> listSupplier;
    private javax.swing.JPanel shippingCompanyPanel;
    private javax.swing.JPanel supplierPanel;
    // End of variables declaration//GEN-END:variables

    private JFrame mainFrame;
    private DefaultListModel<JSupplier> dlmSupplier = new DefaultListModel<>();
    private DefaultListModel<JShippingCompany> dlmSC = new DefaultListModel<>();
    private DefaultListModel<JDealership> dlmDealership = new DefaultListModel<>();
    
    private List<JSupplier> suppliers = new ArrayList<>();
    private List<JShippingCompany> shippingCompanies = new ArrayList<>();
    private List<JDealership> dealerships = new ArrayList<>();
    

    private void initLists() {
        initSupplierList();
        initShippingCompanyList();
        initDealershipList();
    }

    private void initSupplierList() {
        dlmSupplier = (DefaultListModel<JSupplier>) listSupplier.getModel();
        
        dlmSupplier.clear();
        suppliers.clear();
        
        suppliers = JDbFacade.getInstance().readAllSuppliers();

        for (int i = 0; i < suppliers.size(); i++) {
            dlmSupplier.addElement(suppliers.get(i));
        }

        listSupplier.setModel(dlmSupplier);
    }

    private void initShippingCompanyList() {
        dlmSC = (DefaultListModel<JShippingCompany>) listShippingCompany.getModel();
        
        dlmSC.clear();
        shippingCompanies.clear();
        
        shippingCompanies = JDbFacade.getInstance().readAllShippingCompanies();

        for (int i = 0; i < shippingCompanies.size(); i++) {
            dlmSC.addElement(shippingCompanies.get(i));
        }

        listShippingCompany.setModel(dlmSC);
    }

    private void initDealershipList() {
        dlmDealership = (DefaultListModel<JDealership>) listDealership.getModel();
        
        dlmDealership.clear();
        dealerships.clear();
        
        dealerships = JDbFacade.getInstance().readAllDealerships();

        for (int i = 0; i < dealerships.size(); i++) {
            dlmDealership.addElement(dealerships.get(i));
        }

        listDealership.setModel(dlmDealership);
    }
}
