/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.carmaker.view.panel;

import br.carmaker.model.JCar;
import br.carmaker.model.enums.EMenuItem;
import br.carmaker.view.dialog.RegisterDialog;
import br.carmaker.view.list.CarList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Usuário
 */
public class CarPanel extends javax.swing.JPanel {

    /**
     * Creates new form CarPanel
     */
    public CarPanel(JFrame frame) {
        initComponents();
        //initList();
        this.mainFrame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCars = new javax.swing.JList<>();
        btnAddCars = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setText("Lista de Carros:");

        listCars.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listCars.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCarsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listCars);

        btnAddCars.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnAddCars.setText("Adicionar novo");
        btnAddCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCarsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddCars))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCars))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listCarsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCarsValueChanged

    }//GEN-LAST:event_listCarsValueChanged

    private void btnAddCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCarsMouseClicked
        this.setEnabled(false);
        RegisterDialog dialog = new RegisterDialog(mainFrame, false, 2, EMenuItem.CARS);
        dialog.setVisible(true);

        mainFrame.setEnabled(false);
    }//GEN-LAST:event_btnAddCarsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCars;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<JCar> listCars;
    // End of variables declaration//GEN-END:variables

    private JFrame mainFrame;

    private void initList() {
        
        DefaultListModel<JCar> dlm = new DefaultListModel<>();
        
        for (int i = 0; i < 10; i++) {
            JCar car = new JCar();
        
            car.setModel("Fiat uno");
            car.setCostPrice(5000);
            car.setProductionTime(20);
            car.setSalePrice(7000);
            car.setColor("Prata");
            
            dlm.addElement(car);
        }
        
        listCars.setModel(dlm);
        listCars.setCellRenderer(new CarList());
        
    }

}
