/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.carmaker.view.list;

import br.carmaker.model.JCar;
import br.carmaker.model.JConstants;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author felipe
 */
public class CarList extends javax.swing.JPanel implements ListCellRenderer<JCar>{

    /**
     * Creates new form CarList
     */
    public CarList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        lblModel = new javax.swing.JLabel();
        lblProductionTime = new javax.swing.JLabel();
        lblCostPrice = new javax.swing.JLabel();
        lblSalePrice = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));

        lblModel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblModel.setText("Modelo");

        lblProductionTime.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblProductionTime.setText("Tempo de Produção");

        lblCostPrice.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblCostPrice.setText("Preço de Custo");

        lblSalePrice.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblSalePrice.setText("Preço de Venda");

        lblColor.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblColor.setText("Cor");

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBackgroundLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblColor, lblCostPrice, lblModel, lblProductionTime, lblSalePrice});

        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductionTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCostPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalePrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblColor)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCostPrice;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblProductionTime;
    private javax.swing.JLabel lblSalePrice;
    private javax.swing.JPanel panelBackground;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends JCar> list, 
            JCar value, int index, boolean isSelected, boolean hasFocus) {
        
        String model = "<html><strong>" + JConstants.PROTOCOL + ": </strong>" + value.getModel()+ "</html>";
        String prodTime = "<html><strong>" + JConstants.FEEDSTOCK + ": </strong>" + value.getProductionTime()+ "</html>";
        String cost = "<html><strong>" + JConstants.SUPPLIER + ": </strong>" + "R$" + String.format("%.2f", value.getCostPrice()).replace(".", ",") + "</html>";
        String sale = "<html><strong>" + JConstants.STATUS + ": </strong>" + "R$" + String.format("%.2f", value.getSalePrice()).replace(".", ",") + "</html>";
        String color = "<html><strong>" + JConstants.DATE + ": </strong>" + value.getColor() + "</html>";
        
        lblModel.setText(model);
        lblProductionTime.setText(prodTime);
        lblCostPrice.setText(cost);
        lblSalePrice.setText(sale);
        lblColor.setText(color);
        
        if(isSelected){
            panelBackground.setBackground(new Color(29,32,38));
            lblModel.setForeground(Color.WHITE);
            lblProductionTime.setForeground(Color.WHITE);
            lblCostPrice.setForeground(Color.WHITE);
            lblSalePrice.setForeground(Color.WHITE);
            lblColor.setForeground(Color.WHITE);
        }else{
            panelBackground.setBackground(new Color(245,245,246));
            lblModel.setForeground(Color.BLACK);
            lblProductionTime.setForeground(Color.BLACK);
            lblCostPrice.setForeground(Color.BLACK);
            lblSalePrice.setForeground(Color.BLACK);
            lblColor.setForeground(Color.BLACK);
        }
        
        return this;
    }
}
