/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.carmaker.view.list;

import br.carmaker.model.JConstants;
import br.carmaker.model.JDealership;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author felipe
 */
public class DealershipList extends javax.swing.JPanel implements ListCellRenderer<JDealership>{

    /**
     * Creates new form DealershipList
     */
    public DealershipList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        lblCnpj = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblShippingCompany = new javax.swing.JLabel();

        panelBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));

        lblCnpj.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblCnpj.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCnpj.setText("CNPJ");

        lblName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Nome");

        lblAddress.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAddress.setText("Endereço");

        lblType.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblType.setText("Tipo");

        lblShippingCompany.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblShippingCompany.setText("Transportadora");

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShippingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCnpj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShippingCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblType)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblShippingCompany;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel panelBackground;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends JDealership> list, 
            JDealership value, int index, boolean isSelected, boolean hasFocus) {
       
        String name = "<html><strong>" + JConstants.NAME + ": </strong>" + value.getName() + "</html>";
        String address = "<html><strong>" + JConstants.ADDRESS + ": </strong>" + value.getAddress() + "</html>";
        String cnpj = "<html><strong>" + JConstants.CNPJ + ": </strong>" + value.getCnpj() + "</html>";
        String type = "<html><strong>" + JConstants.TYPE + ": </strong>" + value.getType().toString() + "</html>";
        String sComp = "<html><strong>" + JConstants.SHIPPING_COMPANY + ": </strong>" + value.getShippingCompany().getName() + "</html>";
        
        lblName.setText(name);
        lblAddress.setText(address);
        lblCnpj.setText(cnpj);
        lblType.setText(type);
        lblShippingCompany.setText(sComp);
        
        if(isSelected){
            panelBackground.setBackground(new Color(29,32,38));
            lblName.setForeground(Color.WHITE);
            lblAddress.setForeground(Color.WHITE);
            lblCnpj.setForeground(Color.WHITE);
            lblType.setForeground(Color.WHITE);
            lblShippingCompany.setForeground(Color.WHITE);
        }else{
            panelBackground.setBackground(new Color(245,245,246));
            lblName.setForeground(Color.BLACK);
            lblAddress.setForeground(Color.BLACK);
            lblCnpj.setForeground(Color.BLACK);
            lblType.setForeground(Color.BLACK);
            lblShippingCompany.setForeground(Color.BLACK);
        }
        
        return this;
    }
}
