/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.carmaker.view.list;

import br.carmaker.model.util.JConstants;
import br.carmaker.model.JDbFacade;
import br.carmaker.model.JFeedstock;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author felipe
 */
public class FeedstockList extends javax.swing.JPanel implements ListCellRenderer<JFeedstock> {

    /**
     * Creates new form FeedstockList
     */
    public FeedstockList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        lblName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        lblSupplier.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        lblAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        lblCost.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addComponent(lblSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCost, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JPanel panelBackground;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends JFeedstock> list,
            JFeedstock value, int index, boolean isSelected, boolean hasFocus) {
        
        String supplier = "";
        for (int i = 0; i < value.getSuppliers().size(); i++) {
            int id = value.getSuppliers().get(i).getId();
            if(i > 0){
                supplier += ", ";
            }
            supplier += JDbFacade.getInstance().readSupplierById(id).getName();
        }
        
        String name = "<html><strong>" + JConstants.NAME + ": </strong>" + value.getName() + "</html>";
        String amount = "<html><strong>" + JConstants.AMOUNT + ": </strong>" + value.getQuantity()+ "</html>";
        String cost = "<html><strong>" + JConstants.COST + ": </strong>" + "R$" + String.format("%.2f", value.getCost()).replace(".", ",")+ "</html>";
        String sup = "<html><strong>" + JConstants.SUPPLIER + "(es): </strong>" + supplier + "</html>";

        lblName.setText(name);
        lblAmount.setText(amount);
        lblCost.setText(cost);
        lblSupplier.setText(sup);
        
        if(isSelected){
            panelBackground.setBackground(new Color(29,32,38));
            lblName.setForeground(Color.WHITE);
            lblAmount.setForeground(Color.WHITE);
            lblCost.setForeground(Color.WHITE);
            lblSupplier.setForeground(Color.WHITE);
        }else{
            panelBackground.setBackground(new Color(245,245,246));
            lblName.setForeground(Color.BLACK);
            lblAmount.setForeground(Color.BLACK);
            lblCost.setForeground(Color.BLACK);
            lblSupplier.setForeground(Color.BLACK);
        }

        return this;
    }
}
