/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.carmaker.view.list;

import br.carmaker.model.JPlacedOrders;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author felipe
 */
public class PlacedOrderList extends javax.swing.JPanel implements 
        ListCellRenderer<JPlacedOrders>{

    /**
     * Creates new form PlacedOrderList
     */
    public PlacedOrderList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblProtocol = new javax.swing.JLabel();
        lblFeedstock = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        lblProtocol.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblProtocol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProtocol.setText("Protocolo");
        lblProtocol.setBorder(null);
        lblProtocol.setMaximumSize(new java.awt.Dimension(70, 19));

        lblFeedstock.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblFeedstock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFeedstock.setText("Matéria-prima");
        lblFeedstock.setBorder(null);
        lblFeedstock.setMaximumSize(new java.awt.Dimension(80, 19));
        lblFeedstock.setMinimumSize(new java.awt.Dimension(80, 19));

        lblSupplier.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupplier.setText("Fornecedora");
        lblSupplier.setBorder(null);
        lblSupplier.setMinimumSize(new java.awt.Dimension(120, 19));

        lblStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Status");
        lblStatus.setBorder(null);
        lblStatus.setMinimumSize(new java.awt.Dimension(75, 19));

        lblDate.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Data");
        lblDate.setBorder(null);
        lblDate.setMinimumSize(new java.awt.Dimension(75, 19));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblProtocol, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lblFeedstock, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lblSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblFeedstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFeedstock;
    private javax.swing.JLabel lblProtocol;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSupplier;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends JPlacedOrders> list, 
            JPlacedOrders value, int index, boolean isSelected, boolean hasFocus) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        lblProtocol.setText(value.getProtocol());
        lblFeedstock.setText(value.getFeedstock().getName());
        lblSupplier.setText(value.getSupplier().getName());
        lblStatus.setText(value.getStatus().toString());
        lblDate.setText(sdf.format(value.getExpectedDate()));
        
        if(isSelected){
            jPanel2.setBackground(Color.yellow);
        }else{
            jPanel2.setBackground(Color.white);
        }
        
        return this;
    }
    
}
