/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.carmaker.view.list;

import br.carmaker.model.util.JConstants;
import br.carmaker.model.JReceivedOrders;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author felipe
 */
public class ReceivedOrderList extends javax.swing.JPanel implements ListCellRenderer<JReceivedOrders> {

    /**
     * Creates new form RecievedOrderList
     */
    public ReceivedOrderList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        lblProtocol = new javax.swing.JLabel();
        lblCar = new javax.swing.JLabel();
        lblShippingCompany = new javax.swing.JLabel();
        lblDealership = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        panelBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));

        lblProtocol.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblProtocol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProtocol.setText("Protocolo");
        lblProtocol.setMaximumSize(new java.awt.Dimension(70, 19));

        lblCar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblCar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCar.setText("Carro");
        lblCar.setMaximumSize(new java.awt.Dimension(80, 19));
        lblCar.setMinimumSize(new java.awt.Dimension(80, 19));

        lblShippingCompany.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblShippingCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblShippingCompany.setText("Transportadora");
        lblShippingCompany.setMinimumSize(new java.awt.Dimension(120, 19));

        lblDealership.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblDealership.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDealership.setText("Concessionária");
        lblDealership.setMinimumSize(new java.awt.Dimension(120, 19));

        lblStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStatus.setText("Status");
        lblStatus.setMinimumSize(new java.awt.Dimension(75, 19));

        lblDate.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDate.setText("Data");
        lblDate.setMinimumSize(new java.awt.Dimension(75, 19));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShippingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProtocol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDealership, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShippingCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDealership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCar;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDealership;
    private javax.swing.JLabel lblProtocol;
    private javax.swing.JLabel lblShippingCompany;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel panelBackground;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends JReceivedOrders> list, 
            JReceivedOrders value, int index, boolean isSelected, boolean hasFocus) {
        
        SimpleDateFormat sdf = new SimpleDateFormat(JConstants.DATE_FORMAT);
        String protocol = "<html><strong>" + JConstants.PROTOCOL + ": </strong>" + value.getProtocol()+ "</html>";
        String car = "<html><strong>" + JConstants.CAR + ": </strong>" + value.getCar().getModel() + "</html>";
        String sc = "<html><strong>" + JConstants.SHIPPING_COMPANY + ": </strong>" + value.getDealership().getShippingCompany().getName() + "</html>";
        String dealership = "<html><strong>" + JConstants.DEALERSHIP + ": </strong>" + value.getDealership().getName() + "</html>";
        String status = "<html><strong>" + JConstants.STATUS + ": </strong>" + value.getStatus().toString() + "</html>";
        String date = "<html><strong>" + JConstants.DATE + ": </strong>" + sdf.format(value.getExpectedDate()) + "</html>";
        
        lblProtocol.setText(protocol);
        lblCar.setText(car);
        lblShippingCompany.setText(sc);
        lblDealership.setText(dealership);
        lblStatus.setText(status);
        lblDate.setText(date);
        
        if(isSelected){
            panelBackground.setBackground(new Color(29,32,38));
            lblProtocol.setForeground(Color.WHITE);
            lblCar.setForeground(Color.WHITE);
            lblShippingCompany.setForeground(Color.WHITE);
            lblDealership.setForeground(Color.WHITE);
            lblStatus.setForeground(Color.WHITE);
            lblDate.setForeground(Color.WHITE);
        }else{
            panelBackground.setBackground(new Color(245,245,246));
            lblProtocol.setForeground(Color.BLACK);
            lblCar.setForeground(Color.BLACK);
            lblShippingCompany.setForeground(Color.BLACK);
            lblDealership.setForeground(Color.BLACK);
            lblStatus.setForeground(Color.BLACK);
            lblDate.setForeground(Color.BLACK);
        }
        
        return this;
    }
}
