/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.carmaker.view.list;

import br.carmaker.model.JRecievedOrder;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author felipe
 */
public class RecievedOrderList extends javax.swing.JPanel implements ListCellRenderer<JRecievedOrder>{

    /**
     * Creates new form RecievedOrderList
     */
    public RecievedOrderList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblProtocol = new javax.swing.JLabel();
        lblCar = new javax.swing.JLabel();
        lblShippingCompany = new javax.swing.JLabel();
        lblDealership = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        lblProtocol.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblProtocol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProtocol.setText("Protocolo");
        lblProtocol.setBorder(null);
        lblProtocol.setMaximumSize(new java.awt.Dimension(70, 19));

        lblCar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCar.setText("Carro");
        lblCar.setBorder(null);
        lblCar.setMaximumSize(new java.awt.Dimension(80, 19));
        lblCar.setMinimumSize(new java.awt.Dimension(80, 19));

        lblShippingCompany.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblShippingCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShippingCompany.setText("Transportadora");
        lblShippingCompany.setBorder(null);
        lblShippingCompany.setMinimumSize(new java.awt.Dimension(120, 19));

        lblDealership.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblDealership.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDealership.setText("Concessionária");
        lblDealership.setBorder(null);
        lblDealership.setMinimumSize(new java.awt.Dimension(120, 19));

        lblStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Status");
        lblStatus.setBorder(null);
        lblStatus.setMinimumSize(new java.awt.Dimension(75, 19));

        lblDate.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Data");
        lblDate.setBorder(null);
        lblDate.setMinimumSize(new java.awt.Dimension(75, 19));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblProtocol, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lblCar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lblShippingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lblDealership, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblShippingCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblDealership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCar;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDealership;
    private javax.swing.JLabel lblProtocol;
    private javax.swing.JLabel lblShippingCompany;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends JRecievedOrder> list, 
            JRecievedOrder value, int index, boolean isSelected, boolean hasFocus) {
        
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        lblProtocol.setText(value.getProtocol());
        lblCar.setText(value.getCar().getModel());
        lblShippingCompany.setText(value.getCar().getColor());
        lblDealership.setText(Double.toString(value.getCar().getSalePrice()));
        lblStatus.setText(value.getStatus().toString());
        lblDate.setText(sdf.format(value.getExpectedDate()));
        
        if(isSelected){
            jPanel2.setBackground(Color.yellow);
        }else{
            jPanel2.setBackground(Color.white);
        }
        
        return this;
    }
}
