/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.carmaker.view.list;

import br.carmaker.model.util.JConstants;
import br.carmaker.model.JShippingCompany;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author felipe
 */
public class ShippingCompanyList extends javax.swing.JPanel implements ListCellRenderer<JShippingCompany> {

    /**
     * Creates new form ShippingCompanyList
     */
    public ShippingCompanyList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        lblCnpj = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblFleet = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();

        panelBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));

        lblCnpj.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblCnpj.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCnpj.setText("CNPJ");
        lblCnpj.setMinimumSize(new java.awt.Dimension(120, 19));

        lblName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Nome");
        lblName.setMaximumSize(new java.awt.Dimension(70, 19));

        lblAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAmount.setText("Quantidade");
        lblAmount.setMinimumSize(new java.awt.Dimension(75, 19));

        lblFleet.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblFleet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFleet.setText("Frota");
        lblFleet.setMinimumSize(new java.awt.Dimension(75, 19));

        lblAddress.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAddress.setText("Endereço");
        lblAddress.setMaximumSize(new java.awt.Dimension(80, 19));
        lblAddress.setMinimumSize(new java.awt.Dimension(80, 19));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addComponent(lblCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFleet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFleet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblFleet;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel panelBackground;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends JShippingCompany> list,
            JShippingCompany value, int index, boolean isSelected, boolean hasFocus) {

        String name = "<html><strong>" + JConstants.NAME + ": </strong>" + value.getName() + "</html>";
        String address = "<html><strong>" + JConstants.ADDRESS + ": </strong>" + value.getAddress() + "</html>";
        String cnpj = "<html><strong>" + JConstants.CNPJ + ": </strong>" + value.getCnpj() + "</html>";
        String amount = "<html><strong>" + JConstants.AMOUNT + ": </strong>" + Integer.toString(value.getAmount()) + "</html>";
        String fleet = "<html><strong>" + JConstants.FLEET + ": </strong>" + Integer.toString(value.getFleet()) + "</html>";

        lblName.setText(name);
        lblAddress.setText(address);
        lblCnpj.setText(cnpj);
        lblAmount.setText(amount);
        lblFleet.setText(fleet);

        if(isSelected){
            panelBackground.setBackground(new Color(29,32,38));
            lblName.setForeground(Color.WHITE);
            lblAddress.setForeground(Color.WHITE);
            lblCnpj.setForeground(Color.WHITE);
            lblAmount.setForeground(Color.WHITE);
            lblFleet.setForeground(Color.WHITE);
        }else{
            panelBackground.setBackground(new Color(245,245,246));
            lblName.setForeground(Color.BLACK);
            lblAddress.setForeground(Color.BLACK);
            lblCnpj.setForeground(Color.BLACK);
            lblAmount.setForeground(Color.BLACK);
            lblFleet.setForeground(Color.BLACK);
        }

        return this;
    }
}
