/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.carmaker.view.frame;

import br.carmaker.model.enums.EEmployeeType;
import br.carmaker.model.enums.EMenuItem;
import br.carmaker.model.JDbFacade;
import br.carmaker.model.JEmployee;
import br.carmaker.view.dialog.ConfirmDialog;
import br.carmaker.view.panel.EmployeePanel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Usuário
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     * @param id número de identificação do usuário
     */
    public MainFrame(int id) {
        initComponents();
        selectedMenuItem = EMenuItem.HOME.getMenuItem();
        sidebar = panelSideBar.getBackground();

        panelCardEmployee = new EmployeePanel(this);
      
        menuText = new ArrayList<>();
        menuText.add(lblHome);
        menuText.add(lblEmployees);
        menuText.add(lblFeedstock);
        menuText.add(lblCars);
        menuText.add(lblAffiliates);
        menuText.add(lblOrders);
        menuText.add(lblReports);
        
        selectMenuItem(panelCardHome, EMenuItem.HOME.getMenuItem(), menuHome);
        
        JEmployee employee = JDbFacade.getInstance().getEmployeeByID(id);
        lblUser.setText("Bem vindo, "+ employee.getName());
        
        if(employee.getRole() != EEmployeeType.Manager){
            menuEmployees.setVisible(false);
            menuAffiliates.setVisible(false);
        }
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSideBar = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        panelUser = new javax.swing.JPanel();
        lblUserPicture = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        menuHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblImgHome = new javax.swing.JLabel();
        menuEmployees = new javax.swing.JPanel();
        lblEmployees = new javax.swing.JLabel();
        lblImgEmployees = new javax.swing.JLabel();
        menuFeedstock = new javax.swing.JPanel();
        lblImgFeedstock = new javax.swing.JLabel();
        lblFeedstock = new javax.swing.JLabel();
        menuCars = new javax.swing.JPanel();
        lblCars = new javax.swing.JLabel();
        lblImgCars = new javax.swing.JLabel();
        menuAffiliates = new javax.swing.JPanel();
        lblAffiliates = new javax.swing.JLabel();
        lblImgAffiliates = new javax.swing.JLabel();
        menuOrders = new javax.swing.JPanel();
        lblOrders = new javax.swing.JLabel();
        lblImgOrders = new javax.swing.JLabel();
        menuReport = new javax.swing.JPanel();
        lblReports = new javax.swing.JLabel();
        lblImgReports = new javax.swing.JLabel();
        menuLogout = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        lblImgLogout = new javax.swing.JLabel();
        panelView = new javax.swing.JPanel();
        panelCardHome = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblDevelopers = new javax.swing.JLabel();
        panelCardEmployee = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarMaker");
        setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelSideBar.setBackground(new java.awt.Color(29, 32, 38));

        lblHeader.setBackground(new java.awt.Color(29, 32, 38));
        lblHeader.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Car Maker");
        lblHeader.setToolTipText("");
        lblHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHeader.setOpaque(true);
        lblHeader.setPreferredSize(new java.awt.Dimension(215, 60));

        panelUser.setOpaque(false);
        panelUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelUser.add(lblUserPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 80));

        lblUser.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Bem Vindo, Usuário");
        panelUser.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 170, 60));

        menuHome.setBackground(new java.awt.Color(0, 0, 0));
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuHomeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuHomeMouseEntered(evt);
            }
        });
        menuHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setText(EMenuItem.HOME.getMenuItem());
        menuHome.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 170, 50));

        lblImgHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        menuHome.add(lblImgHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        menuEmployees.setBackground(new java.awt.Color(29, 32, 38));
        menuEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEmployeesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuEmployeesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuEmployeesMouseEntered(evt);
            }
        });
        menuEmployees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmployees.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblEmployees.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployees.setText(EMenuItem.EMPLOYEES.getMenuItem());
        menuEmployees.add(lblEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 170, 50));

        lblImgEmployees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/employee.png"))); // NOI18N
        menuEmployees.add(lblImgEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        menuFeedstock.setBackground(new java.awt.Color(29, 32, 38));
        menuFeedstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFeedstockMouseClicked(evt);
            }
        });
        menuFeedstock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgFeedstock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgFeedstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/feedstock.png.png"))); // NOI18N
        menuFeedstock.add(lblImgFeedstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        lblFeedstock.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblFeedstock.setForeground(new java.awt.Color(255, 255, 255));
        lblFeedstock.setText(EMenuItem.FEEDSTOCK.getMenuItem());
        menuFeedstock.add(lblFeedstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 0, 170, 50));

        menuCars.setBackground(new java.awt.Color(29, 32, 38));
        menuCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCarsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuCarsMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuCarsMouseEntered(evt);
            }
        });
        menuCars.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCars.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblCars.setForeground(new java.awt.Color(255, 255, 255));
        lblCars.setText(EMenuItem.CARS.getMenuItem());
        menuCars.add(lblCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 170, 50));

        lblImgCars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgCars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/car.png"))); // NOI18N
        menuCars.add(lblImgCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        menuAffiliates.setBackground(new java.awt.Color(29, 32, 38));
        menuAffiliates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAffiliatesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuAffiliatesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuAffiliatesMouseEntered(evt);
            }
        });
        menuAffiliates.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAffiliates.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblAffiliates.setForeground(new java.awt.Color(255, 255, 255));
        lblAffiliates.setText(EMenuItem.AFFILIATES.getMenuItem());
        menuAffiliates.add(lblAffiliates, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 170, 50));

        lblImgAffiliates.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgAffiliates.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/affiliates.png"))); // NOI18N
        menuAffiliates.add(lblImgAffiliates, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        menuOrders.setBackground(new java.awt.Color(29, 32, 38));
        menuOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOrdersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuOrdersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuOrdersMouseEntered(evt);
            }
        });
        menuOrders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrders.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblOrders.setForeground(new java.awt.Color(255, 255, 255));
        lblOrders.setText(EMenuItem.ORDERS.getMenuItem());
        menuOrders.add(lblOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 170, 50));

        lblImgOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order.png"))); // NOI18N
        menuOrders.add(lblImgOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        menuReport.setBackground(new java.awt.Color(29, 32, 38));
        menuReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportMouseEntered(evt);
            }
        });
        menuReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReports.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblReports.setForeground(new java.awt.Color(255, 255, 255));
        lblReports.setText(EMenuItem.REPORT.getMenuItem());
        menuReport.add(lblReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 170, 50));

        lblImgReports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/report.png"))); // NOI18N
        menuReport.add(lblImgReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        menuLogout.setBackground(new java.awt.Color(29, 32, 38));
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLogoutMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLogoutMouseEntered(evt);
            }
        });
        menuLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogout.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText(EMenuItem.LOGOUT.getMenuItem());
        menuLogout.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 170, 50));

        lblImgLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        menuLogout.add(lblImgLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        javax.swing.GroupLayout panelSideBarLayout = new javax.swing.GroupLayout(panelSideBar);
        panelSideBar.setLayout(panelSideBarLayout);
        panelSideBarLayout.setHorizontalGroup(
            panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideBarLayout.createSequentialGroup()
                .addGroup(panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(menuHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuEmployees, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuFeedstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuCars, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuAffiliates, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuOrders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuLogout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelSideBarLayout.setVerticalGroup(
            panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideBarLayout.createSequentialGroup()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuFeedstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuAffiliates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelView.setBackground(new java.awt.Color(255, 255, 255));
        panelView.setLayout(new java.awt.CardLayout());

        panelCardHome.setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setFont(new java.awt.Font("Harlow Solid Italic", 0, 100)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("Car Maker");

        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText("Versão 1.0");

        lblDevelopers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDevelopers.setText("Desenvolvido por Felipe Martins e Rafael Magalhães");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
            .addComponent(lblDevelopers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVersion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDevelopers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVersion)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCardHomeLayout = new javax.swing.GroupLayout(panelCardHome);
        panelCardHome.setLayout(panelCardHomeLayout);
        panelCardHomeLayout.setHorizontalGroup(
            panelCardHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
            .addGroup(panelCardHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCardHomeLayout.setVerticalGroup(
            panelCardHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(panelCardHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCardHomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelView.add(panelCardHome, "card2");

        panelCardEmployee.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout panelCardEmployeeLayout = new javax.swing.GroupLayout(panelCardEmployee);
        panelCardEmployee.setLayout(panelCardEmployeeLayout);
        panelCardEmployeeLayout.setHorizontalGroup(
            panelCardEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        panelCardEmployeeLayout.setVerticalGroup(
            panelCardEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        panelView.add(panelCardEmployee, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelView, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(panelSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelSideBar.setLocation(-210, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        selectMenuItem(panelCardHome, EMenuItem.HOME.getMenuItem(), menuHome);
    }//GEN-LAST:event_menuHomeMouseClicked

    private void menuHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseEntered
        panelMenuHover(menuHome, 1, EMenuItem.HOME.getMenuItem());
    }//GEN-LAST:event_menuHomeMouseEntered

    private void menuHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseExited
        panelMenuHover(menuHome, 0, EMenuItem.HOME.getMenuItem());
    }//GEN-LAST:event_menuHomeMouseExited

    private void menuEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmployeesMouseClicked
        selectMenuItem(panelCardEmployee, EMenuItem.EMPLOYEES.getMenuItem(), menuEmployees);
    }//GEN-LAST:event_menuEmployeesMouseClicked

    private void menuEmployeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmployeesMouseEntered
        panelMenuHover(menuEmployees, 1, EMenuItem.EMPLOYEES.getMenuItem());
    }//GEN-LAST:event_menuEmployeesMouseEntered

    private void menuEmployeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmployeesMouseExited
        panelMenuHover(menuEmployees, 0, EMenuItem.EMPLOYEES.getMenuItem());
    }//GEN-LAST:event_menuEmployeesMouseExited

    private void menuCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarsMouseClicked
        //        selectMenuItem(panelCardCars, EMenuItem.CARS.getMenuItem(), menuEmployees);
    }//GEN-LAST:event_menuCarsMouseClicked

    private void menuCarsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarsMouseEntered
        panelMenuHover(menuCars, 1, EMenuItem.CARS.getMenuItem());
    }//GEN-LAST:event_menuCarsMouseEntered

    private void menuCarsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarsMouseExited
        panelMenuHover(menuCars, 0, EMenuItem.CARS.getMenuItem());
    }//GEN-LAST:event_menuCarsMouseExited

    private void menuFeedstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFeedstockMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFeedstockMouseClicked

    private void menuOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrdersMouseClicked
        //        selectMenuItem(panelCardOrders, EMenuItem.ORDERS.getMenuItem(), menuEmployees);
    }//GEN-LAST:event_menuOrdersMouseClicked

    private void menuOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrdersMouseEntered
        panelMenuHover(menuOrders, 1, EMenuItem.ORDERS.getMenuItem());
    }//GEN-LAST:event_menuOrdersMouseEntered

    private void menuOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrdersMouseExited
        panelMenuHover(menuOrders, 0, EMenuItem.ORDERS.getMenuItem());
    }//GEN-LAST:event_menuOrdersMouseExited

    private void menuAffiliatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAffiliatesMouseClicked
        //        selectMenuItem(panelCardffiliates, EMenuItem.AFFILIATES.getMenuItem(), menuEmployees);
    }//GEN-LAST:event_menuAffiliatesMouseClicked

    private void menuAffiliatesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAffiliatesMouseEntered
        panelMenuHover(menuAffiliates, 1, EMenuItem.AFFILIATES.getMenuItem());
    }//GEN-LAST:event_menuAffiliatesMouseEntered

    private void menuAffiliatesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAffiliatesMouseExited
        panelMenuHover(menuAffiliates, 0, EMenuItem.AFFILIATES.getMenuItem());
    }//GEN-LAST:event_menuAffiliatesMouseExited

    private void menuReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportMouseClicked
        //        selectMenuItem(panelCardReport, EMenuItem.REPORT.getMenuItem(), menuReport);
    }//GEN-LAST:event_menuReportMouseClicked

    private void menuReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportMouseEntered
        panelMenuHover(menuReport, 1, EMenuItem.REPORT.getMenuItem());
    }//GEN-LAST:event_menuReportMouseEntered

    private void menuReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportMouseExited
        panelMenuHover(menuReport, 0, EMenuItem.REPORT.getMenuItem());
    }//GEN-LAST:event_menuReportMouseExited

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        logout();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseEntered
        panelMenuHover(menuLogout, 1, lblLogout.getText());
    }//GEN-LAST:event_menuLogoutMouseEntered

    private void menuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseExited
        panelMenuHover(menuLogout, 0, lblLogout.getText());
    }//GEN-LAST:event_menuLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(-1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAffiliates;
    private javax.swing.JLabel lblCars;
    private javax.swing.JLabel lblDevelopers;
    private javax.swing.JLabel lblEmployees;
    private javax.swing.JLabel lblFeedstock;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblImgAffiliates;
    private javax.swing.JLabel lblImgCars;
    private javax.swing.JLabel lblImgEmployees;
    private javax.swing.JLabel lblImgFeedstock;
    private javax.swing.JLabel lblImgHome;
    private javax.swing.JLabel lblImgLogout;
    private javax.swing.JLabel lblImgOrders;
    private javax.swing.JLabel lblImgReports;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblOrders;
    private javax.swing.JLabel lblReports;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserPicture;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuAffiliates;
    private javax.swing.JPanel menuCars;
    private javax.swing.JPanel menuEmployees;
    private javax.swing.JPanel menuFeedstock;
    private javax.swing.JPanel menuHome;
    private javax.swing.JPanel menuLogout;
    private javax.swing.JPanel menuOrders;
    private javax.swing.JPanel menuReport;
    private javax.swing.JPanel panelCardEmployee;
    private javax.swing.JPanel panelCardHome;
    private javax.swing.JPanel panelSideBar;
    private javax.swing.JPanel panelUser;
    private javax.swing.JPanel panelView;
    // End of variables declaration//GEN-END:variables

    private String selectedMenuItem;
    private final Color sidebar;
    private final List<JLabel> menuText;
    
    private void panelMenuHover(JPanel panel, int mouseState, String labelName) {
        //Mouse entered
        if (mouseState == 1) {
            panel.setBackground(Color.BLACK);
        } else { //Mouse exited
            if (!selectedMenuItem.equals(labelName)) {
                panel.setBackground(panelSideBar.getBackground());
            }
        }
    }

    private void selectMenuItem(JPanel panel, String labelName, JPanel menuItem) {
        
        panelView.removeAll();
        panelView.add(panel);
        panelView.repaint();
        panelView.revalidate();
             
        for (int i = 0; i < menuText.size(); i++) {
            JLabel jl = menuText.get(i);            
            if(jl.getText().equals(labelName)){                
                selectedMenuItem = labelName;
                jl.getParent().setBackground(Color.black);
            }else{
                jl.getParent().setBackground(sidebar);
            }
        }  
        
    }

    private void logout() {
        ConfirmDialog confirmDialog = new ConfirmDialog(this, false);

        confirmDialog.setHeaderText("Confirmar saída do sistema?");
        confirmDialog.changeDialog();
        confirmDialog.setLogout(true);
        confirmDialog.setVisible(true);

        this.setEnabled(false);
    }
}
